# Site settings
title: Simple Primate
description: "Simple Primate is the online home of James Williamson, lynda.com author, speaker and occasional web developer."
baseurl: "" 
url: "http://www.simpleprimate.com" 
tagline: Monkeying around with code
author: "James Williamson"

# Build settings
gems: [jekyll-paginate]
highlighter: rouge
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
include: user_images
